
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zabegaev99.
--- DateTime: 28.03.2018 18:33
---


M = {}


local function getn(T)
    local l = 0
    for k, v in ipairs(T) do
        if (type(v) == "table") then
            l = l + getn(T[k])

        else
            l = l + 1
        end
    end
    return l
end


local function getFontSize (button, coef)
  if coef == nil then
    coef = .5
  end
  return coef * ((button.contentWidth > button.contentHeight) and button.contentWidth or button.contentHeight)
end


M.getFontSize = getFontSize
M.getn = getn
return M